# Плагин "InfernCustomEggs" Версия плагина: 1.0v
# Разработчик (По всем вопросам) -> Егор Татаркин (Ник в майне: EG_SH_NOT) vk.com/egortatarkin : @theegorhick (Telegram)
#
# Канал Великого Егшота -> t.me/egashotina

item: # Настройка кастомного предмета
  material: PUFFERFISH_SPAWN_EGG # Материал
  name: "&#EFD715&lО&#F1DB2B&lс&#F3DF40&lк&#F5E356&lо&#F7E86C&lл&#F9EC82&lо&#FBF097&lч&#FDF4AD&lн&#FDEE95&lо&#FCE97E&lе &#FCDE4F&lя&#FCD837&lй&#FBD320&lц&#FBCD08&lо" # Название
  lore: # Описание
    - "&f Получайте осколочные яйца "
    - "&f Добывая вещи из грузов."
    - " "
    - "&7Особенности:"
    - "&#EFD715 - вы можете обменять эти яйца"
    - "  &#EFD715  на ценные яйца призыва"
    - "  &#EFD715  прописав команду: /eggs"

spawn-eggs: # Выдача рандомных яиц
  # Категории МОЖНО МЕНЯТЬ И ДОБАВЛЯТЬ СВОИ! Пример:
  default: # Название категории (можно поставить любое, главное в menu.yml изменить!)
    - "give %player PIG_SPAWN_EGG 1" # Яйца призыва
  Lite:
    - "give %player CREEPER_SPAWN_EGG 1"
    - "give %player WITHER_SKELETON_SPAWN_EGG 1"
  Epic:
    - "give %player EVOKER_SPAWN_EGG 1"
    - "give %player ZOMBIFIED_PIGLIN_SPAWN_EGG 1"

settings: # Настройка плагина
  sound-complete: ENTITY_PUFFER_FISH_BLOW_UP
  sound-not-eggs: BLOCK_ANVIL_PLACE

message: # Сообщение
  not-eggs: "&#FD0000▶&f Недостаточно &#FD0000осколочных&f яиц!"
  give-eggs: "&#EFD715▶&f Вы обменяли &#EFD715яйцо!"

